### ISSUE TITLE
Add support for 3.2 data file version

### ISSUE THREAD

**Issue by simast** [51Degrees/51degrees.node#26]
The TrieV3 data file is now marked as deprecated, but the new TrieV32 is not supported with current NodeJS bindings.

`Warning: Device data file is not correct`

**Comment by RainbowPony** [comment]
Experiencing the same exact problem: 
I've got 51Degrees-EnterpriseV3_2.trie file and npm module  51 degrees v1.8.1.
The error pops up, when I try to create a parser with that file and all enterprise properties:
```
var deviceDataDetectionComponentConfig = {
  file: global.ROOT_DIR + '/vendors/51degrees/enterprise/51Degrees-EnterpriseV3_2.trie',
  properties: require('51degrees').ALL_ENTERPRISE_PROPERTIES
};

Parser = require('51degrees').Parser;
global._51DegreesParser = new Parser(this.options.file, require('51degrees').ALL_PREMIUM_PROPERTIES);
```
And the error is as following: `Device data file is not correct`

**Comment by yorkie** [comment]
Ah this might need the support from the new version of 51degrees api, am i right @51Degrees/nodeteam?

**Comment by ben51degrees** [comment]
There have been fairly significant changes to the 51Degrees API in V3.2, which is why the node API is locked to V3.1. We are in the final stages of development of a new V3.2 node API which uses SWIG (the same as our other C based APIs) to bring all new features added to the C API straight into node. This is targeted for release in August. However, if you can't wait that long and wish to try out the current version, let me know, and it can be arranged.

**Comment by RainbowPony** [comment]
@ben51degrees, thanks for the quick reply. If it is not very difficult for you, I'd prefer to try the current version, but I'll be keeping an eye on the updates to jump to the newest version in August.

**Comment by ben51degrees** [comment]
@RainbowPony I have attached a quick patch which will enable you to use 3.2 data files (both Pattern and Trie). Bear in mind that I have only given this a quick functionality test though. This will give you the option to use the 3.2 data files, or you can use the current API without the patch with V3 data files.
I will send you over the development version of the 3.2 API later today, that way the option is there if you need it.
[0001-FEAT-MAJOR-Added-ability-to-use-V3.2-data-files.patch.zip](https://github.com/51Degrees/51degrees.node/files/373837/0001-FEAT-MAJOR-Added-ability-to-use-V3.2-data-files.patch.zip)

**Comment by RainbowPony** [comment]
@ben51degrees, thank you so much!

**Comment by ben51degrees** [comment]
@RainbowPony That's alright. Give me a shout if you need anything else.

**Comment by RainbowPony** [comment]
@ben51degrees, I'm gonna try to stick to that patch you gave me, well at least I'll try to, but if it won't be enough - will do just what you've told me to, so thanks once again.

**Comment by ben51degrees** [comment]
@RainbowPony Thought I would let you know on here in case you haven't seen already, we have released our new node.js API. It is available in our [GitHub repository](https://github.com/51Degrees/Device-Detection) and on [NPM](https://www.npmjs.com/package/fiftyonedegreescore).

**Comment by RainbowPony** [comment]
@ben51degrees , thanks you so much again! 
And, actually, I've encountered another thing, when using new version of the library: if I want to use any  list of properties from "51degrees" npm module (enterprise, premium, or lite AFTER formatting in to string of course), I get an error, saying that
`Aborted (core dumped)`
And if I try using only several properties, such as "IsMobile|DeviceType" it ends up working just fine.
I close my match after every time, I've finished using it. 
Perhaps, you could help me. Thank you in advance.

**Comment by ben51degrees** [comment]
@RainbowPony , I have tried to recreate this issue but with no success.
What I have tried is running the following:
```
FODOld = require('51degrees');
FOD = require('fiftyonedegreescore);
propertyArray = FODOld.ALL_PROPERTIES;
propertyString = "";
propertyArray.forEach(function(property) {
    propertyString += "|";
    propertyString += property;
});
propertyString = propertyString.split(1, propertyString.length);
config = {
    'dataFile': require('fiftyonedegreeslitepattern'),
    'properties': propertyString
}
provider = new FOD.provider(config);
device = provider.getMatch('some User-Agent');
propertyArray.forEach(function(property) {
    console.log(match.getValue(property));
}
```

Is this similar to what you are doing, or does the error occur somewhere else in the code?

**Comment by RainbowPony** [comment]
@ben51degrees, exactly, but, well, instead of ALL_PROPERTIES, I've used ENTERPRISE ones. And that resulted in the aforementioned error. 
Actually, I've been able to find a way to avoid that error: when creating a new Provider, I do not specify desired properties, and get them one-by-one after getMatch function:
          `lib = require('fiftyonedegreescore');
          51DegreesProvider = new lib.provider({
            dataFile: this.options.dataFile
          });
          51DegreesProvider.properties = this.options.properties;
          ... 
          var resOrigin = 51DegreesProvider.getMatch(userAgentString);
          51DegreesProvider.properties.forEach(function(property) {
              resp[property.toLowerCase()] = resOrigin[property];
          });
          resOrigin.close();`

Another issue, I'm experiencing right now, is that new version of the library is using a lot of resources of my machine. For instance, RAM usage had gone up from 4 to 11 GB's. Does it have any connection to the way, I'm using the library, how do you think?

**Comment by ben51degrees** [comment]
@RainbowPony initialising the provider in this way means that all properties in the data set are initialised. Then using `provider.availableProperties` will give you an array of all the properties in your data set. This may be a better way to get them if you want all the properties?

Could you post what your properties string is when you were passing is in to the provider constructor? That might help to find why this is happening.

With memory usage, 11GB is much more than the library should be using. When using a cache of 10000 and a pool of 100 I get about 380MB on my machine. What cache and pool sizes are you using?
Just a thought, is resp defined globally? As assigning all the values that would otherwise be disposed of to a variable that would stay around could lead to a memory leak.

**Comment by RainbowPony** [comment]
@ben51degrees, thank you for the quick reply. I'm using this list of properties.
[enterprise.json.zip](https://github.com/51Degrees/51degrees.node/files/479689/enterprise.json.zip)
Actually, I think there is gotta be my error somewhere, so I'm gonna give it a couple more tries... Sorry to bother you.)

**Comment by vapongit** [comment]
"Segmentation fault" bugfix

[segfault.patch.txt](https://github.com/51Degrees/51degrees.node/files/527271/segfault.patch.txt)

**Comment by RainbowPony** [comment]
@vapongit, thank you for the reply.) 
Kinda did the same when I had been struggling with the module.

**Comment by ben51degrees** [comment]
@vapongit @RainbowPony Thanks for finding where the seg fault was, and appologies for the late response.
Could you let me know which compiler and node version you are using? I will look at this patch and do some testing, it seems like a fairly straight forward change of type so there shouldn't be a problem getting this included in our next release.

**Comment by vapongit** [comment]
Node
node -v
v5.12.0

GCC
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.9/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 4.9.2-10' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --with-arch-32=i586 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.9.2 (Debian 4.9.2-10)
